# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='Channels',
        ),
        migrations.AlterModelTable(
            name='player',
            table='Players',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Questions',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Teams',
        ),
    ]
