# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170804_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.CharField(max_length=100),
        ),
    ]
